### ISSUE TITLE
URL Verification

### ISSUE THREAD

**Issue by ssmid** [jhermsmeier/fints-institute-db#2]
How can I make sure the url is real and not an attacker's one? Or is FinTS secure against such kinds of mitm attacks?

**Comment by jhermsmeier** [comment]
The same way you'd verify any TLS session I suppose; by verifying the certificate chain, and checking against certificate revocation lists etc. – which is something your networking stack or library usually does for you. I don't remember if the FinTS protocol itself has any particular safeguards in that respect, it probably does, I'd recommend reading [the specification](https://www.hbci-zka.de/spec/4_1.htm).

If you're concerned about the truthfulness of the data contained in this repository, or are planning on using this for any kind of financial product, I would strongly recommend registering with the [HBCI ZKA / SIZ](https://www.hbci-zka.de/register/hersteller.htm) to obtain the up-to-date data from there. The data in this repository is only updated on a best-effort basis, when I find the time to do so.

**Comment by ssmid** [comment]
Not that I wanted to accuse you or anything, but the information in this repo could be out-of-date, as you say, and an attacker could register an old domain and obtain a valid certificate for it. The certificate could only be trusted if it also included the bank's name or if the domain was 100% up-to-date.
Btw, I was more thinking about an open source finance application, but the registration authority might not be happy about it, I could imagine. I wished they would just throw away this application key stuff and make it all public, since you can probably steal most application keys through basic reverse engineering.

**Comment by ssmid** [comment]
At least you could trust an open source application to not send your financial data half around the world.

**Comment by jhermsmeier** [comment]
The registration authority is perfectly fine with that, most open source applications / libraries get their data from there (this one included), given that it is the source of truth for this particular dataset. You're just not allowed to re-publish the files they give you, but derivates are fine iirc. Registration is also not complicated or anything, they will assign you an id for your registration and send you the data w/ periodic updates – no application keys or any of that involved.

**Comment by ssmid** [comment]
Yeah, I meant that application id. As far as I remember, they require you to name a company that is responsible for the application. But I'm a bit surprised that they allow the application including the key to be open source. However, thanks for all the information on the topic!

**Comment by jhermsmeier** [comment]
You're welcome! Oh yes, true – I had forgotten; they do ask for a company / Gewerbe, but I suspect one could haggle that out. My experience with them so far as been very friendly and forthcoming.
